// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvpP-VDAVmqqM8E0cLo7OM5Kp5wYlq6tY',
    appId: '1:748242399678:web:9e0ac0e3a1bcebb19fc9ef',
    messagingSenderId: '748242399678',
    projectId: 'uts-desvilia',
    authDomain: 'uts-desvilia.firebaseapp.com',
    databaseURL: 'https://uts-desvilia-default-rtdb.firebaseio.com',
    storageBucket: 'uts-desvilia.appspot.com',
    measurementId: 'G-Y1SN0JC7VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp4VkIsMV0-udsa7gZkoiiB4mZpOUS8Gk',
    appId: '1:748242399678:android:2eb51d13daa00bef9fc9ef',
    messagingSenderId: '748242399678',
    projectId: 'uts-desvilia',
    databaseURL: 'https://uts-desvilia-default-rtdb.firebaseio.com',
    storageBucket: 'uts-desvilia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX3kLEF86hacRbryxCML1VqZXnKx32oS8',
    appId: '1:748242399678:ios:99c3c957141b6e809fc9ef',
    messagingSenderId: '748242399678',
    projectId: 'uts-desvilia',
    databaseURL: 'https://uts-desvilia-default-rtdb.firebaseio.com',
    storageBucket: 'uts-desvilia.appspot.com',
    iosBundleId: 'com.example.desvilia2125240094Uts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX3kLEF86hacRbryxCML1VqZXnKx32oS8',
    appId: '1:748242399678:ios:99c3c957141b6e809fc9ef',
    messagingSenderId: '748242399678',
    projectId: 'uts-desvilia',
    databaseURL: 'https://uts-desvilia-default-rtdb.firebaseio.com',
    storageBucket: 'uts-desvilia.appspot.com',
    iosBundleId: 'com.example.desvilia2125240094Uts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvpP-VDAVmqqM8E0cLo7OM5Kp5wYlq6tY',
    appId: '1:748242399678:web:a91127e5079fbb5b9fc9ef',
    messagingSenderId: '748242399678',
    projectId: 'uts-desvilia',
    authDomain: 'uts-desvilia.firebaseapp.com',
    databaseURL: 'https://uts-desvilia-default-rtdb.firebaseio.com',
    storageBucket: 'uts-desvilia.appspot.com',
    measurementId: 'G-BEP9GWKWDG',
  );
}
